### ISSUE TITLE
Error in connection with QRadar

### ISSUE THREAD

**Issue by robben-ar** [hkromer/qradar-hemp#1]
Hello Hubert Kromer,
Thank you very much for this development.
I am trying to export the data of QRadar to a server with ELK but the following error is throwing at the script:

`[root@qradar ~]# python2.7 qradar-hemp.py

Traceback (most recent call last):
  File "qradar-hemp.py", line 448, in <module>
    main()
  File "qradar-hemp.py", line 440, in main
    checkServices()
  File "qradar-hemp.py", line 234, in checkServices
    if int(applianceType[:2]) in qradarApplianceTypeAllInOne:
ValueError: invalid literal for int() with base 10: 'so'`

Regards.-

**Comment by robben-ar** [comment]
Now you are returning this error:


> root@debian-ruben:/opt/qradar-hemp# python2 qradar-hemp.py
> 
> Traceback (most recent call last):
>   File "qradar-hemp.py", line 447, in <module>
>     main()
>   File "qradar-hemp.py", line 439, in main
>     checkServices()
>   File "qradar-hemp.py", line 229, in checkServices
>     qradarDeploymentId = qradarDeploymentIdFetch()
>   File "qradar-hemp.py", line 162, in qradarDeploymentIdFetch
>     confNva = StringIO.StringIO()
> AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

**Comment by robben-ar** [comment]
Hi Hkromer
I was able to connect to the QRadar server but I would not be bringing all the information.
I have the ssh_authority configured but it hangs when bringing the different states (isAlreadyRunning, checkServices, checkLogSourceStatistics, checkOffenseStatistics, checkRuleStatistics, checkQRadarVersion).
I will verify Postgres credentials.
Regards.-
